### ISSUE TITLE
集群情况下怎么部署呢

### ISSUE THREAD

**Issue by caihuoche** [baidu/uid-generator#11]
看了看代码 网上也找了找资料, 愣是没找到集群的使用方法.  集群下可以不重复 并且有序吗

**Comment by caihuoche** [comment]
看了下具体实现, 一次默认生成8096个. 集群下虽然可以通过机器码来决定唯一, 但是并不是俩台机器有序.

**Comment by vision-ken** [comment]
看了下代码，得出以下结论：
- DefaultUidGenerator：多个节点同一秒内ID无序，不同秒的ID是有序的。
- CachedUidGenerator：多个节点ID无序。
