### ISSUE TITLE
“paddingFactor”没有set方法，是否可以正常初始化bean？

### ISSUE THREAD

**Issue by ghost** [baidu/uid-generator#12]
你好，
查看了下源代码，应该是spring基于XML通过set方式进行bean实例化。但类“CachedUidGenerator”中的成员变量“paddingFactor”没有set方法：setPaddingFactor()。不晓得我理解的对不对？

**Comment by baozhi** [comment]
setPaddingFactor()遗漏掉了，未配置的话不影响使用。感兴趣的同学可以提个pr
