### ISSUE TITLE
能否有个spring boot 的 demo

### ISSUE THREAD

**Issue by github-gage** [baidu/uid-generator#2]
spring boot + jpa

**Comment by baozhi** [comment]
【spring boot】
demo基于原生spring，迁移至spring boot也比较方便，这里就不提供spring boot的demo了

【jpa】
workerID的分配，内置实现为通过mybatis基于mysql的实现`DisposableWorkerIdAssigner`
如需使用jpa，可自定义`WorkerIdAssigner`实现

谢谢！

**Comment by github-gage** [comment]
@baozhi 
谢谢

**Comment by vision-ken** [comment]
@github-gage 
我写了个spring boot版本的：https://github.com/prong-projects/prong-uid, 你可参考一下。
