### ISSUE TITLE
并发出现异常 ：java.lang.IllegalArgumentException: Curosr not in can take status

### ISSUE THREAD

**Issue by yanglikun** [baidu/uid-generator#26]
代码如下所示：10个线程，一个获取2千万。
timeBits：29
workerBits: 21
seqBits: 13
![image](https://user-images.githubusercontent.com/1728527/53858151-02ae1f00-4014-11e9-9901-c3241cd62f62.png)

**Comment by yuzhaopeng** [comment]
获取的太快了，生产者还没来及生成新的uid，就会导致这个问题
