### ISSUE TITLE
生成ID全部是负数

### ISSUE THREAD

**Issue by Feng-xs** [baidu/uid-generator#29]
uidGenerator-timeBits: 23
uidGenerator-workerBits: 31
uidGenerator-seqBits: 9
uidGenerator-epochStr: '2018-12-22'
uidGenerator-boostPower: 3
uidGenerator-paddingFactor: 50
uidGenerator-scheduleInterval: 60
当参数为这些时会出现负数

**Comment by teneous** [comment]
你的del值有31536000ms，对应2 ^ 24 = 16777216 2 ^ 25 = 33554432 长度8
因此你的timebits值必须至少25位吧
