### ISSUE TITLE
既然用了jdk1.8 为什么不用@contended注解避免伪共享

### ISSUE THREAD

**Issue by Yaccc** [baidu/uid-generator#3]
如题

**Comment by baozhi** [comment]
`@contended`是java8官方解决方案，但对于user classpath加载的类，需要配合`-XX:-RestrictContended`JVM启动参数。
为了不强制JVM启动参数、以及便于应用者适配jdk7，故未采用`@contended`

谢谢！

**Comment by Yaccc** [comment]
可是你们的代码里面到处都是jdk8的语法，怎么兼容jdk7？

**Comment by Yaccc** [comment]
![image](https://user-images.githubusercontent.com/5906306/27847236-197c4a20-616f-11e7-97bb-16625caa8779.png)
而且updateAndGet只有jdk8的api有

**Comment by baozhi** [comment]
![image](https://user-images.githubusercontent.com/4001686/27849699-ce39c282-6181-11e7-910a-12c3803825e3.png)
对，`updateAndGet`JDK8才有，但是内部实现用到的`get()``compareAndSet(long expect, long update)`都是JDK7兼容的

其余用到lambda、@FunctionalInterface都是比较好替换的

**Comment by baozhi** [comment]
先关了，有问题新开issue讨论
@Yaccc 期待美团的开源，互相学习优秀的代码^_^

**Comment by Yaccc** [comment]
@baozhi 顺便搭车问一下dlock的续租怎么保证一定成功的
