### ISSUE TITLE
不是很理解，时间只占用28位，机器id占22位，为什么要这么设计呢？

### ISSUE THREAD

**Issue by jiangrongbo** [baidu/uid-generator#34]
时间只占用28位，只能要8年，机器id占22位，有朋友能解释下为什么吗？

**Comment by XngPro** [comment]
> 时间只占用28位，只能要8年，机器id占22位，有朋友能解释下为什么吗？

https://github.com/baidu/uid-generator#tips

**Comment by XngPro** [comment]
> 时间只占用28位，只能要8年，机器id占22位，有朋友能解释下为什么吗？

可以修改的，参考 https://github.com/baidu/uid-generator#tips
