### ISSUE TITLE
Flag-RingBuffer是否有必要存在

### ISSUE THREAD

**Issue by zhongjunliang** [baidu/uid-generator#45]
既然有tail、cursor分别表示生产，消费的offset，直接根据这个两个变量确定put, take的位置不就好了吗？为什么还需要Flag-RingBuffer，以及判断里面相应位置的状态？

**Comment by kaixuanzhang123** [comment]
同样的疑问

**Comment by yuzhaopeng** [comment]
两个变量不太好确定，环形数组，他两的索引时大时小，并发时候可能还会出现空跑了一圈
