### ISSUE TITLE
CachedUidGenerator can provide 6000 thousand/s throughput, how can it happen?

### ISSUE THREAD

**Issue by ericmoshare** [baidu/uid-generator#5]
我的测试数据如下: 

 JMH 1.17.5 (released 249 days ago, please consider updating!)
 VM version: JDK 1.8.0_101, VM 25.101-b13
 VM invoker: D:\apps\jdk\jdk1.8.0_101\jre\bin\java.exe
 VM options: -Didea.launcher.port=7537 -Didea.launcher.bin.path=D:\apps\JetBrains\IntelliJ IDEA 2016.3.1\bin -Dfile.encoding=UTF-8
 Warmup: 5 iterations, 5 s each
 Measurement: 20 iterations, 5 s each
 Timeout: 10 min per iteration
 Threads: 20 threads, will synchronize iterations
 Benchmark mode: Throughput, ops/time
 Benchmark: com.vpal.beifu.customs.benchmarktest.IdGeneratorBenchmarkTest.benchPrecondition

 Run progress: 0.00% complete, ETA 00:02:05
 Fork: 1 of 1
 Warmup Iteration

 Warmup Iteration   2: 91892.284 ops/s
 Warmup Iteration   3: 91975.161 ops/s
 Warmup Iteration   4: 92341.250 ops/s
 Warmup Iteration   5: 99186.817 ops/s
Iteration   1: 90499.371 ops/s
Iteration   2: 86129.521 ops/s
Iteration   3: 75192.984 ops/s
Iteration   4: 78517.215 ops/s
Iteration   5: 78064.527 ops/s
Iteration   6: 78340.945 ops/s
Iteration   7: 75036.587 ops/s
Iteration   8: 77089.315 ops/s
Iteration   9: 78202.288 ops/s
Iteration  10: 75584.124 ops/s
Iteration  11: 74410.960 ops/s
Iteration  12: 76744.887 ops/s
Iteration  13: 74803.554 ops/s
Iteration  14: 75628.749 ops/s
Iteration  15: 74925.918 ops/s
Iteration  16: 76541.028 ops/s
Iteration  17: 77475.313 ops/s
Iteration  18: 75880.433 ops/s
Iteration  19: 77597.357 ops/s
Iteration  20: 75894.316 ops/s

Result "com.vpal.beifu.customs.benchmarktest.IdGeneratorBenchmarkTest.benchPrecondition":
  77627.970 ±(99.9%) 3419.012 ops/s [Average]
  (min, avg, max) = (74410.960, 77627.970, 90499.371), stdev = 3937.339
  CI (99.9%): [74208.958, 81046.981] (assumes normal distribution)

 Run complete. Total time: 00:02:09

Benchmark                                    Mode  Cnt      Score      Error  Units
IdGeneratorBenchmarkTest.benchPrecondition  thrpt   20  77627.970 ± 3419.012  ops/s

**Comment by baozhi** [comment]
用的哪种UidGenerator实现？

**Comment by baozhi** [comment]
建议参考下[CachedUidGeneratorTest](https://github.com/baidu/uid-generator/blob/master/src/test/java/com/baidu/fsg/uid/CachedUidGeneratorTest.java)，其中`testParallelGenerate()`方法用于测试多线程吞吐量。
关闭日志`VERBOSE=false`、以及唯一性检查。在MacBook Pro（4核2.7GHz Intel Core i5, 8G DDR3）环境下，8线程生成5亿UID，QPS即可达600万。

**Comment by baozhi** [comment]
建议参考下[CachedUidGeneratorTest](https://github.com/baidu/uid-generator/blob/master/src/test/java/com/baidu/fsg/uid/CachedUidGeneratorTest.java)，其中`testParallelGenerate()`方法用于测试多线程吞吐量。
关闭日志`VERBOSE=false`、以及唯一性检查。在MacBook Pro（4核2.7GHz Intel Core i5, 8G DDR3）环境下，8线程生成5亿UID，QPS即可达600万。
