### ISSUE TITLE
为什么只有Tail、Cursor指针、Flag-RingBuffer中采用了CacheLine 补齐方式？

### ISSUE THREAD

**Issue by csonezp** [baidu/uid-generator#50]
UID-RingBuffer不需要吗？

**Comment by yuzhaopeng** [comment]
我理解是因为在并发获取uid的情况下，uid-RingBuffer 只读不写，但是 Flag-RingBuffer 是读写一起的，读完立马就写，如果不做CacheLine填充，就会出现相邻的两个flag 加载到同一个CacheLine中，两个线程同时写flag 出现竞争，然后影响并发性能
