### ISSUE TITLE
是否有必要使用双buffer

### ISSUE THREAD

**Issue by wangyunzhong123** [baidu/uid-generator#56]
本身id的生成是纯内存操作，靠移位就可以完成。buffer的意义个人感觉不大，而且put和take的时候做很多异步操作更是对cpu的一种浪费。

求问CachedUidGenerator的意义何在呢？？

**Comment by GourdErwa** [comment]
- cache 可预借时间，吞吐量可大于序列最大值
- 你说的位移完成，怎么完成呢，读可以控制为非并发，写肯定要并发的，位移如何保证并发

**Comment by gearcode** [comment]
我也不太明白，是否因为默认时间粒度为秒，导致每秒内的并发度非常高，所以需要ringbuffer？
我以前一直用毫秒的，sequence原子类型自增就好了，这样性能也不差吧？

**Comment by DanielFeb** [comment]
并发很高的情况下，如果没有buffer，一个变量自增，cpu cache line的写冲突会很严重。 而且像 CAS 这种机制适合冲突较少的情况，如果太多线程在同时自旋，那么长时间循环会导致 CPU 开销很大。
