### ISSUE TITLE
getId获取时间比较长

### ISSUE THREAD

**Issue by tim1888** [baidu/uid-generator#58]
@baozhi 咨询个性能问题啊
本地压测通过http获取id时，有几次耗时超过300ms(还有超过1s的)，这个不是在内存连续存储的么，怎么还这么慢？
是一遍获取id，一点存储id导致？
配置：
       CachedUidGenerator、boostPower=7
       -Xms12G -Xmx12G
       server.tomcat.max-threads=1000

       jemeter 500线程，吞吐量9K左右

**Comment by nickChenyx** [comment]
你这个测试可能 http 链接及对应 java 线程处理速度有问题
