### ISSUE TITLE
是否可以考虑另一种workerid的分配方案

### ISSUE THREAD

**Issue by icanfly** [baidu/uid-generator#6]
默认实现的是重启拿取新的workerid的方式，我觉得这块可以优化。可以基于唯一不变性约束来减少workerid的消耗，比如拿机器mac+机器ip地址作为唯一的方式来确定workerid，通过mysql insert on duplicate update模式，如果该唯一的标识(mac+ip)不存在则插入成功，得到新的workerid，如果已经存在，则获取原有的id信息，这样可以减少workerid的消耗，那么workerid的位数就可以不需要那么多位，比如可能只需要15bit，就可以实现32768台机器的部署规模，将更多的位数留给timeBits和seqBits，提高使用年限和并发度，同时可以引入heartbeat心跳，对于一些下架的机器根据失效的心跳从worker表中踢除，以节约更多的机器。

以上是我个人的见解，并根据以上思路实现了一个ReusableWorkerIdAssigner，如有不对的地方，请指正。如果可以，我也可以提一个PR。

**Comment by zljgit** [comment]
单机部署多个实例或多个应用在一台主机上都依赖他生成id 就会出问题吧

**Comment by icanfly** [comment]
@zljgit  Idworker应该是一个服务集群，一台机器部署一个就没有这样的问题。如果在一台物理机环境下部署docker环境，docker也会有独立的IP和mac，所以我觉得这块问题不大。

**Comment by carvinhappy** [comment]
@icanfly 这样每次重启取新的workerId应该是为了解决重启时服务器时间发生回拨的问题。

**Comment by 80808746** [comment]
111

**Comment by xingguang2013** [comment]
是否可以在应用的启动脚本中添加 `-Dwork.id` 参数，这样也可以避免同一台机器多个应用部署使用问题，也不会有 `work.id` 增加的情况。

**Comment by zer0Black** [comment]
这个方案会导致时间回拨产生的ID重复，请考虑如下一种场景：
服务实例关闭，时间回拨，重启服务实例
这时候重启实例，如果workid不变，可能会造成ID重复的问题。
但如果每次重启workid都变，即便时间回拨了，也可通过workid来保证生成生成ID不重复

**Comment by pwh19920920** [comment]
@zer0Black 你这个想法没错，但是可能存在workid不够用的情况。

**Comment by kangwen** [comment]
> @zer0Black 你这个想法没错，但是可能存在workid不够用的情况。

只能调整worker位数了， 默认前面的delta seconds才8.5年，worker nodes如果22bit即使支持420万次 也是徒劳。况且产线的一个发号服务怎么会天天重启，一个月重启一次都嫌多。所以worker nodes必须要降位，worker nodes借3位给delta seconds。 delta seconds就能支持68年，这样worker nodes还能支持52万次。即使发号器集群有20台机器，平均一天重启一遍 也可能支持70年。 这才是一个均衡的思路。

**Comment by Viyond** [comment]
workerId的复用方案建议考虑下。

**Comment by iamforrest** [comment]
复用感觉很简单的吧，用redis inc取余数不就完事了？你不可能同时启动420万台服务器吧？

```
public long assignWorkerId() {
        return redisService.increment(REDIS_KEY_WC_ID) % MAX_VALUE;
}
```
