### ISSUE TITLE
64位虚机里 CacheLine 填充过长问题

### ISSUE THREAD

**Issue by yuzhaopeng** [baidu/uid-generator#68]
在 `PaddedAtomicLong` 类中为了避免伪共享问题，填充了6了long类型的属性。

但是在64位虚机下，对象头会占用16个byte ， 所以对象的实际大小就是 ：  对象头（16byte） + 填充long（6*8 byte ）+ 自身long（8 byte）  = 72 byte  ， 此时已经超出了一个CacheLine 64 byte 。

所以在64位虚机下，填充long 是否 5个就够了？

**Comment by xiaobox** [comment]
我也觉得不对劲，
![](https://secure2.wostatic.cn/static/8PsoWTpR19obQGtuh99MTL/image.png) 对象头至少也有12个，

**Comment by xiaobox** [comment]
> 在 `PaddedAtomicLong` 类中为了避免伪共享问题，填充了6了long类型的属性。
> 
> 但是在64位虚机下，对象头会占用16个byte ， 所以对象的实际大小就是 ： 对象头（16byte） + 填充long（6*8 byte ）+ 自身long（8 byte） = 72 byte ， 此时已经超出了一个CacheLine 64 byte 。
> 
> 所以在64位虚机下，填充long 是否 5个就够了？

64 位系统超过缓存行的 64 字节也无所谓，只要保证不同线程不操作同一缓存行就可以
