### ISSUE TITLE
总共没几条sql,建议直接使用jdbc,不要在使用mybatis等框架

### ISSUE THREAD

**Issue by davidricardo1026** [baidu/uid-generator#71]
你好,非常感谢你的工作,我这里有个小小的建议,总共没几条sql,写一下sql就好了,现在依赖了mybatis以后,增加了复杂度,不利于项目的依赖

**Comment by ok123zxx** [comment]
好建议，不过这个项目应该是人走茶凉了

**Comment by toshawn** [comment]
> 好建议，不过这个项目应该是人走茶凉了

可以参看我封装的百度uid的 SpringBoot Starter
