### ISSUE TITLE
控制台日志频繁打印

### ISSUE THREAD

**Issue by yejingweiye** [baidu/uid-generator#78]
Ready to padding buffer lastSecond:1658228866. RingBuffer
Rejected putting buffer for uid:5334933497364480. RingBuffer
End to padding buffer lastSecond:1658228867. RingBuffer

这三条日志一直在打印，是否正常，能否屏蔽？

**Comment by toshawn** [comment]
你应该是设置了 scheduleInterval 这个值,它会在后台开启定时任务线程去检查缓存队列是否有空闲,如果你需要可以不设置这个值,那么就不会打印这个日志了
