### ISSUE TITLE
CachedUidGenerator尽可能地保持时间最新

### ISSUE THREAD

**Issue by usc** [baidu/uid-generator#8]
目前CachedUidGenerator在初始化的时候lastSecond用的是当前秒，后续的只是在此基础上+1（不在依赖时钟，并发高的时候还可以预借），不过如果ID生成很少，那么就可能导致生成的ID（解析后）于实际的时间相差很多。
虽然ID相对有序，但是有些时候还是需要根据ID大致知道相应的时间。目前这样ID里面的时间就不需要很准确。
比如在schedule周期性调整lastSecond，或者其他方法。

**Comment by ChinaLym** [comment]
这算是性能/资源 和 精度 的一种取舍策略吧。采用逻辑时钟替代实际时钟，可以有效的利用每个逻辑时间戳的序列。且若频繁调用获取时钟回对性能产生较大影响。
如果需要从id获取时间，推荐自行扩展吧（周期性矫正），并不是默认的实现能满足所有业务场景。

**Comment by ChinaLym** [comment]
已收到~感谢来信！
