### ISSUE TITLE
A component required a bean of type 'com.github.wujun234.uid.impl.CachedUidGenerator' that could not be found.

### ISSUE THREAD

**Issue by mhiStrat** [baidu/uid-generator#84]
运行环境：springboot 3.0.1

Description:

A component required a bean of type 'com.github.wujun234.uid.impl.CachedUidGenerator' that could not be found.

Action:

Consider defining a bean of type 'com.github.wujun234.uid.impl.CachedUidGenerator' in your configuration.

**Comment by toshawn** [comment]
容器内没有找到这个类型的 Bean ,将 CachedUidGenerator 注册到 Spring 容器即可.
