### ISSUE TITLE
报错 UidGenerateExption ：java.RuntimeExecption ：Rejected take buffer . RingBuffer [bufferize=65536,tail=65536,cursor=65536,paddingThreshold=32768]

### ISSUE THREAD

**Issue by wswmx1** [baidu/uid-generator#90]
请问在使用过程中报这样的错误是哪方面的原因造成，使用的环境是 mybatispuls + oracle

**Comment by toshawn** [comment]
<img width="965" alt="image" src="https://github.com/baidu/uid-generator/assets/74593234/cb5ddbf5-e6ac-4123-9c0c-05436bfc0ab7">
通常是因为获取 uid 的速度大于生成 uid 的速度才会抛出此异常

**Comment by 361387670** [comment]
同样报这错误，怎么解决了？

**Comment by wswmx1** [comment]
重启，还有就是更新jar包版本



***@***.***
 
发件人： MySpring
发送时间： 2023-10-10 15:26
收件人： baidu/uid-generator
抄送： xiaohetu; Author
主题： Re: [baidu/uid-generator] 报错 UidGenerateExption ：java.RuntimeExecption ：Rejected take buffer . RingBuffer [bufferize=65536,tail=65536,cursor=65536,paddingThreshold=32768] (Issue #90)
同样报这错误，怎么解决了？

**Comment by 361387670** [comment]
你好，请问更新到哪个版本可以解决

**Comment by wswmx1** [comment]
好像是2点几的版本，具体是哪个版本现在看不到，公司封装了的工具包



***@***.***
 
发件人： MySpring
发送时间： 2023-10-10 16:41
收件人： baidu/uid-generator
抄送： xiaohetu; Author
主题： Re: [baidu/uid-generator] 报错 UidGenerateExption ：java.RuntimeExecption ：Rejected take buffer . RingBuffer [bufferize=65536,tail=65536,cursor=65536,paddingThreshold=32768] (Issue #90)
你好，请问更新到哪个版本可以解决
