### ISSUE TITLE
机器 id，最多可支持约 420w 次机器启动

### ISSUE THREAD

**Issue by 9-4-6** [baidu/uid-generator#91]
如果超过420W启动，有没有方案，机器id，可以提供复用策略吗，为什么要有420W限制呢。

**Comment by yuzhuweng** [comment]
420万的限制在哪里呢 没有看懂

**Comment by 9-4-6** [comment]
> 420万的限制在哪里呢 没有看懂

![image](https://github.com/baidu/uid-generator/assets/32507511/6102dfba-3e43-43d1-b261-0e500740dbc9)
