### ISSUE TITLE
时间戳运算代码是不是写错了

### ISSUE THREAD

**Issue by yuzhuweng** [baidu/uid-generator#92]
这里是不是写错了
![image](https://github.com/baidu/uid-generator/assets/100658542/9148e3d0-faff-409b-8110-c07d7340966a)

**Comment by dugreen** [comment]
这里没错吧，sing + time + worker + seq，如果找到时间戳，就需要左移 worker + seq 位，同理 seq 不需要左移，因为他就在最右边。
